version: '3.1'

services:
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    networks:
      - spring-network
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: 'postgres:14-alpine'
    container_name: db-postgres
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    networks:
      - spring-network
    volumes:
      - db-volume:/var/lib/postgresql/data

networks:
  spring-network:

volumes:
  db-volume:
